Repository azhang7886/cs166_Proj, pull requests merged in 2024-06, with the labels that each got.

#2 ADD: created the CreateUser function and a queries.sql
  java/classes/GameRental.class
  java/src/GameRental.java
  sql/src/load_data.sql
  sql/src/queries.sql
Labels: enhancement

#9 Py1u/project
  java/src/GameRental.java
  sql/src/queries.sql
Labels: enhancement, help wanted

#7 UPDATE: added half of function updateProfile
  java/src/GameRental.java
  sql/src/queries.sql
Labels: enhancement

#15 total gui updates
  java/src/GameRental.java
Labels: documentation, enhancement, help wanted

#13 Azhang7886/sql changes to placeOrder to py1u/project
  java/src/GameRental.java
  sql/src/queries.sql
Labels: bug, enhancement

#18 Py1u/project code clean for file to main
  java/src/GameRental.java
Labels: documentation, enhancement

#19 added main changes to pull req to azhang7886/sql
  java/src/GameRental.java
Labels: documentation, enhancement

#21 added main branch changes for new functions to py1u/project
  java/src/GameRental.java
  sql/src/create_tables.sql
  sql/src/queries.sql
Labels: enhancement, help wanted

#23 main changes to py1u/main
  java/src/GameRental.java
  sql/src/queries.sql
Labels: documentation

#25 Azhang7886/sql changes to py1u/project
  data/trackinginfo.csv
  java/src/GameRental.java
  sql/src/queries.sql
Labels: bug, documentation, help wanted

#26 Py1u/project
  java/src/GameRental.java
Labels: bug, documentation, help wanted

#27 Py1u/project one change to main
  java/src/GameRental.java
Labels: bug
